### ISSUE TITLE
Wording for output in Test_Procedures.py, Procedure 1.2

### ISSUE THREAD

**Issue by mrcrnkovich** [AICPA-AuditDataAnalytics2018/ADS---Python-Example-#6]
For Procedure 1.2 (Test_procedures_1, procedure 2), there is a print line (line 37) that says:
```python
        writer.writerow(['Amounts of following %a journal entries do not match their amounts in Log File:' %(len(In_LOG_not_in_GL))])
```

I don't think this is accurate, since we're not comparing the Amount of the JE, just the JE_ID.

**Comment by danshorstein** [comment]
i'm ok with changing it, go for it
