### ISSUE TITLE
Refactor Test_Procedures.py New Feature

### ISSUE THREAD

**Issue by mrcrnkovich** [AICPA-AuditDataAnalytics2018/ADS---Python-Example-#7]
I'm looking to refactor Test_Procedures.py. I've started to do so on my forked branch, but before I make too many changes, I wanted to run a simple feature by you. I'm thinking about adding:
``` python
def __init__(self, GL, Log, GL_Column, Log_Column, output_folder):
    # save values as part of the object
    self.GL = GL
```

So that we can instantiate an object for each GL, i.e.:
```python
GL_Client = Test_1_Procedures(GL = General_Ledger_MMYYYY,
                               Log = Log_File,  GL_Column = "Journal_ID",
                               Log_Column = "Journal_ID")

GL_Client.check_for_gaps_in_JE_ID()
```
Or we also add a function that will run all of the tests for you:
```python
GL_Client.runAll()

# Or don't even save the object
Test_1_Procedures(GL = General_Ledger_MMYYYY,
            Log = Log_File,  GL_Column = "Journal_ID",
            Log_Column = "Journal_ID").runAll()

```

**Comment by danshorstein** [comment]
ok with me, but i'd prefer if we follow typical Pythonic snake_case rather than camelCase or something else with any capital letters.
